import { TranscodeJob } from '../models/TranscodeJob';
import { Movie } from '../models/Movie';
import { Episode } from '../models/Episode';
import { transcodeToHls } from './transcoder';
import logger from './logger';
import fs from 'fs';

interface QueueTask {
  jobId: string;
  inputPath: string;
  subfolder?: string;
}

class TranscodeQueue {
  private queue: QueueTask[] = [];
  private activeJobId: string | null = null;
  private isProcessing = false;

  /**
   * Enqueues a new transcode job
   */
  public enqueue(jobId: string, inputPath: string, subfolder?: string) {
    this.queue.push({ jobId, inputPath, subfolder });
    logger.info(`Enqueued transcode job ${jobId}. Queue length: ${this.queue.length}`);
    this.processNext();
  }

  /**
   * Processes the next job in the queue
   */
  private async processNext() {
    if (this.isProcessing) return;
    if (this.queue.length === 0) {
      this.isProcessing = false;
      this.activeJobId = null;
      return;
    }

    this.isProcessing = true;
    const task = this.queue.shift()!;
    this.activeJobId = task.jobId;

    logger.info(`Starting transcode job ${task.jobId} from queue.`);

    try {
      // 1. Update TranscodeJob status to processing
      const job = await TranscodeJob.findOneAndUpdate(
        { hlsMasterPlaylistUrl: new RegExp(task.jobId) },
        { status: 'processing', progress: 0 },
        { new: true }
      );

      if (!job) {
        throw new Error(`TranscodeJob metadata not found in database for jobId: ${task.jobId}`);
      }

      // If already linked to Movie/Episode, update their status to processing too
      if (job.movieId) {
        await Movie.findByIdAndUpdate(job.movieId, { status: 'processing' });
      }
      if (job.episodeId) {
        await Episode.findByIdAndUpdate(job.episodeId, { status: 'processing' });
      }

      // 2. Run FFmpeg transcoding
      let lastProgressUpdate = 0;
      const result = await transcodeToHls(task.inputPath, task.jobId, async (progress) => {
        // Throttle progress updates in the DB to avoid locking/overload (e.g. update every 5% progress difference)
        if (progress.percent - lastProgressUpdate >= 5 || progress.percent === 100) {
          lastProgressUpdate = progress.percent;
          await TranscodeJob.updateOne(
            { _id: job._id },
            { progress: progress.percent }
          );
          logger.info(`Job ${task.jobId} transcode progress: ${progress.percent}%`);
        }
      }, task.subfolder);

      // 3. Update database model to completed
      await TranscodeJob.updateOne(
        { _id: job._id },
        {
          status: 'completed',
          progress: 100,
          hlsMasterPlaylistUrl: result.hlsMasterPlaylistUrl,
          qualities: result.qualities,
          autoGeneratedPosterUrl: result.posterUrl || '',
        }
      );

      // Reload job to see if it got linked to Movie/Episode during processing
      const updatedJob = await TranscodeJob.findById(job._id);
      if (updatedJob) {
        if (updatedJob.movieId) {
          const movieUpdate: any = {
            status: 'draft', // Sets back to draft so admin can preview and publish
            hlsMasterPlaylistUrl: result.hlsMasterPlaylistUrl,
            qualities: result.qualities,
          };
          if (result.posterUrl) {
            movieUpdate.poster = result.posterUrl;
          }
          await Movie.findByIdAndUpdate(updatedJob.movieId, movieUpdate);
          logger.info(`Updated Movie ${updatedJob.movieId} with completed HLS stream and poster.`);
        }
        if (updatedJob.episodeId) {
          const episodeUpdate: any = {
            status: 'draft',
            hlsMasterPlaylistUrl: result.hlsMasterPlaylistUrl,
            qualities: result.qualities,
          };
          if (result.posterUrl) {
            episodeUpdate.thumbnail = result.posterUrl;
          }
          await Episode.findByIdAndUpdate(updatedJob.episodeId, episodeUpdate);
          logger.info(`Updated Episode ${updatedJob.episodeId} with completed HLS stream and thumbnail.`);
        }
      }

      logger.info(`Transcode job ${task.jobId} completed successfully.`);
    } catch (err: any) {
      logger.error(`Transcode job ${task.jobId} failed. Error: ${err.message}`);

      // Update DB to failed
      const job = await TranscodeJob.findOneAndUpdate(
        { hlsMasterPlaylistUrl: new RegExp(task.jobId) },
        { status: 'failed', error: err.message },
        { new: true }
      );

      if (job) {
        if (job.movieId) {
          await Movie.findByIdAndUpdate(job.movieId, { status: 'failed' });
        }
        if (job.episodeId) {
          await Episode.findByIdAndUpdate(job.episodeId, { status: 'failed' });
        }
      }
    } finally {
      // Double check clean up of local raw file if still present
      try {
        if (fs.existsSync(task.inputPath)) {
          fs.unlinkSync(task.inputPath);
        }
      } catch (err) {
        // Safe to ignore
      }

      // Clean up temporary raw R2 file if it was streamed from R2
      if (task.inputPath.startsWith('http')) {
        try {
          let r2Key = '';
          if (task.inputPath.includes('/api/stream/r2/')) {
            r2Key = decodeURIComponent(task.inputPath.split('/api/stream/r2/')[1]);
          } else if (process.env.R2_PUBLIC_URL && task.inputPath.includes(process.env.R2_PUBLIC_URL)) {
            r2Key = decodeURIComponent(task.inputPath.split(process.env.R2_PUBLIC_URL + '/')[1]);
          }

          if (r2Key && r2Key.startsWith('raw-videos/')) {
            const { deleteFile } = require('./r2Service');
            await deleteFile(r2Key);
            logger.info(`Cleaned up raw R2 upload file: ${r2Key}`);
          }
        } catch (err: any) {
          logger.error(`Failed to clean up raw R2 upload file from URL: ${task.inputPath}. Error: ${err.message}`);
        }
      }

      this.isProcessing = false;
      this.activeJobId = null;
      // Process next in queue
      this.processNext();
    }
  }

  /**
   * Get active processing job and queue information
   */
  public getStatus() {
    return {
      activeJobId: this.activeJobId,
      queueLength: this.queue.length,
      isProcessing: this.isProcessing,
      pendingJobs: this.queue.map((q) => q.jobId),
    };
  }
}

export const transcodeQueue = new TranscodeQueue();
export default transcodeQueue;
