import { Request, Response } from 'express';
import { Episode } from '../models/Episode';
import { TranscodeJob } from '../models/TranscodeJob';
import { ApiError } from '../utils/apiError';
import { asyncHandler } from '../utils/asyncHandler';
import { Types } from 'mongoose';
import { deleteFile, deleteDir } from '../utils/r2Service';

function extractStorageKey(url: string | undefined): string | null {
  if (!url) return null;
  if (url.includes('/uploads/')) {
    return url.split('/uploads/')[1];
  }
  try {
    const parsed = new URL(url);
    const pathname = parsed.pathname;
    const R2_BUCKET = process.env.R2_BUCKET;
    if (R2_BUCKET && pathname.startsWith(`/${R2_BUCKET}/`)) {
      return pathname.slice(R2_BUCKET.length + 2);
    }
    return pathname.startsWith('/') ? pathname.slice(1) : pathname;
  } catch (err) {
    return null;
  }
}

function extractJobId(hlsUrl: string | undefined): string | null {
  if (!hlsUrl) return null;
  const match = hlsUrl.match(/transcoded\/([^\/]+(?:\/[^\/]+)?)\/master\.m3u8/);
  return match ? match[1] : null;
}

export const listEpisodesForSeries = asyncHandler(async (req: Request, res: Response) => {
  const episodes = await Episode.find({ series: req.params.seriesId }).sort({ season: 1, episodeNumber: 1 });
  res.json({ success: true, data: { episodes } });
});

export const createEpisode = asyncHandler(async (req: Request, res: Response) => {
  const hlsUrl = req.body.hlsMasterPlaylistUrl;
  let initialStatus = 'draft';
  let qualities: any[] = [];

  const job = await TranscodeJob.findOne({ hlsMasterPlaylistUrl: hlsUrl });
  if (job) {
    if (job.status === 'completed') {
      initialStatus = 'draft';
      qualities = job.qualities;
    } else if (job.status === 'failed') {
      initialStatus = 'failed';
    } else {
      initialStatus = 'processing';
    }
  }

  const episodeData = {
    ...req.body,
    qualities,
    status: initialStatus,
    series: req.params.seriesId,
  };

  if (job && job.autoGeneratedPosterUrl && !req.body.thumbnail) {
    episodeData.thumbnail = job.autoGeneratedPosterUrl;
  }

  const episode = await Episode.create(episodeData);

  if (job) {
    job.episodeId = episode._id as Types.ObjectId;
    await job.save();
  }

  res.status(201).json({ success: true, data: { episode } });
});

export const updateEpisode = asyncHandler(async (req: Request, res: Response) => {
  const episode = await Episode.findById(req.params.id);
  if (!episode) throw new ApiError(404, 'Episode not found');

  const hlsUrl = req.body.hlsMasterPlaylistUrl;
  if (hlsUrl && hlsUrl !== episode.hlsMasterPlaylistUrl) {
    const job = await TranscodeJob.findOne({ hlsMasterPlaylistUrl: hlsUrl });
    if (job) {
      job.episodeId = episode._id as Types.ObjectId;
      await job.save();

      if (job.autoGeneratedPosterUrl && !req.body.thumbnail) {
        req.body.thumbnail = job.autoGeneratedPosterUrl;
      }

      if (job.status === 'completed') {
        req.body.status = 'draft';
        req.body.qualities = job.qualities;
      } else if (job.status === 'failed') {
        req.body.status = 'failed';
        req.body.qualities = [];
      } else {
        req.body.status = 'processing';
        req.body.qualities = [];
      }
    }
  }

  Object.assign(episode, req.body);
  await episode.save();
  res.json({ success: true, data: { episode } });
});

export const deleteEpisode = asyncHandler(async (req: Request, res: Response) => {
  const episode = await Episode.findById(req.params.id);
  if (!episode) throw new ApiError(404, 'Episode not found');

  // Clean up associated files
  if (episode.thumbnail) {
    const key = extractStorageKey(episode.thumbnail);
    if (key) await deleteFile(key);
  }
  if (episode.hlsMasterPlaylistUrl) {
    const jobId = extractJobId(episode.hlsMasterPlaylistUrl);
    if (jobId) {
      await deleteDir(`transcoded/${jobId}`);
      await TranscodeJob.deleteOne({ hlsMasterPlaylistUrl: episode.hlsMasterPlaylistUrl });
    }
  }

  await Episode.findByIdAndDelete(req.params.id);
  res.json({ success: true, message: 'Episode deleted successfully' });
});
