import { Response } from 'express';
import { Movie } from '../models/Movie';
import { TranscodeJob } from '../models/TranscodeJob';
import { ApiError } from '../utils/apiError';
import { asyncHandler } from '../utils/asyncHandler';
import { slugify } from '../utils/slugify';
import { AuthenticatedRequest } from '../middleware/auth';
import { Request } from 'express';
import { Types } from 'mongoose';
import { deleteFile, deleteDir } from '../utils/r2Service';

function extractStorageKey(url: string | undefined): string | null {
  if (!url) return null;
  if (url.includes('/uploads/')) {
    return url.split('/uploads/')[1];
  }
  try {
    const parsed = new URL(url);
    const pathname = parsed.pathname;
    const R2_BUCKET = process.env.R2_BUCKET;
    if (R2_BUCKET && pathname.startsWith(`/${R2_BUCKET}/`)) {
      return pathname.slice(R2_BUCKET.length + 2);
    }
    return pathname.startsWith('/') ? pathname.slice(1) : pathname;
  } catch (err) {
    return null;
  }
}

function extractJobId(hlsUrl: string | undefined): string | null {
  if (!hlsUrl) return null;
  const match = hlsUrl.match(/transcoded\/([^\/]+(?:\/[^\/]+)?)\/master\.m3u8/);
  return match ? match[1] : null;
}

export const createMovie = asyncHandler(async (req: AuthenticatedRequest, res: Response) => {
  const baseSlug = slugify(req.body.title);
  let slug = baseSlug;
  let suffix = 1;
  while (await Movie.exists({ slug })) {
    slug = `${baseSlug}-${suffix++}`;
  }

  const hlsUrl = req.body.hlsMasterPlaylistUrl;
  let initialStatus = 'draft';
  let qualities: any[] = [];

  const job = await TranscodeJob.findOne({ hlsMasterPlaylistUrl: hlsUrl });
  if (job) {
    if (job.status === 'completed') {
      initialStatus = 'draft';
      qualities = job.qualities;
    } else if (job.status === 'failed') {
      initialStatus = 'failed';
    } else {
      initialStatus = 'processing';
    }
  }

  const movieData = {
    ...req.body,
    slug,
    qualities,
    status: initialStatus,
    createdBy: req.user!.userId,
  };

  if (job && job.autoGeneratedPosterUrl && !req.body.poster) {
    movieData.poster = job.autoGeneratedPosterUrl;
  }

  const movie = await Movie.create(movieData);

  if (job) {
    job.movieId = movie._id as Types.ObjectId;
    await job.save();
  }

  res.status(201).json({ success: true, data: { movie } });
});

export const updateMovie = asyncHandler(async (req: AuthenticatedRequest, res: Response) => {
  const movie = await Movie.findById(req.params.id);
  if (!movie) throw new ApiError(404, 'Movie not found');

  if (req.body.title && req.body.title !== movie.title) {
    const baseSlug = slugify(req.body.title);
    let slug = baseSlug;
    let suffix = 1;
    while (await Movie.exists({ slug, _id: { $ne: movie._id } })) {
      slug = `${baseSlug}-${suffix++}`;
    }
    (req.body as any).slug = slug;
  }

  const hlsUrl = req.body.hlsMasterPlaylistUrl;
  if (hlsUrl && hlsUrl !== movie.hlsMasterPlaylistUrl) {
    const job = await TranscodeJob.findOne({ hlsMasterPlaylistUrl: hlsUrl });
    if (job) {
      job.movieId = movie._id as Types.ObjectId;
      await job.save();
      
      if (job.autoGeneratedPosterUrl && !req.body.poster) {
        req.body.poster = job.autoGeneratedPosterUrl;
      }
      
      if (job.status === 'completed') {
        req.body.status = 'draft';
        req.body.qualities = job.qualities;
      } else if (job.status === 'failed') {
        req.body.status = 'failed';
        req.body.qualities = [];
      } else {
        req.body.status = 'processing';
        req.body.qualities = [];
      }
    }
  }

  Object.assign(movie, req.body);
  await movie.save();

  res.json({ success: true, data: { movie } });
});

export const deleteMovie = asyncHandler(async (req: Request, res: Response) => {
  const movie = await Movie.findById(req.params.id);
  if (!movie) throw new ApiError(404, 'Movie not found');

  // Delete storage assets
  if (movie.poster) {
    const key = extractStorageKey(movie.poster);
    if (key) await deleteFile(key);
  }
  if (movie.banner) {
    const key = extractStorageKey(movie.banner);
    if (key) await deleteFile(key);
  }
  if (movie.trailerUrl) {
    const key = extractStorageKey(movie.trailerUrl);
    if (key) await deleteFile(key);
  }
  if (movie.hlsMasterPlaylistUrl) {
    const jobId = extractJobId(movie.hlsMasterPlaylistUrl);
    if (jobId) {
      await deleteDir(`transcoded/${jobId}`);
      await TranscodeJob.deleteOne({ hlsMasterPlaylistUrl: movie.hlsMasterPlaylistUrl });
    }
  }

  await Movie.findByIdAndDelete(req.params.id);
  res.json({ success: true, message: 'Movie deleted successfully' });
});

export const getMovieById = asyncHandler(async (req: Request, res: Response) => {
  const movie = await Movie.findById(req.params.id).populate('genres categories');
  if (!movie) throw new ApiError(404, 'Movie not found');
  res.json({ success: true, data: { movie } });
});

export const getMovieBySlug = asyncHandler(async (req: Request, res: Response) => {
  const movie = await Movie.findOneAndUpdate(
    { slug: req.params.slug, status: 'published' },
    { $inc: { views: 1 } },
    { new: true }
  ).populate('genres categories');
  if (!movie) throw new ApiError(404, 'Movie not found');
  res.json({ success: true, data: { movie } });
});

export const listMovies = asyncHandler(async (req: Request, res: Response) => {
  const { page, limit, search, genre, category, status, featured, trending } = req.query as any;

  const filter: Record<string, unknown> = {};
  if (search) filter.$text = { $search: search as string };
  if (genre) filter.genres = genre;
  if (category) filter.categories = category;
  if (status) filter.status = status;
  if (featured !== undefined) filter.isFeatured = featured;
  if (trending !== undefined) filter.isTrending = trending;

  const skip = (page - 1) * limit;

  const [movies, total] = await Promise.all([
    Movie.find(filter).sort({ createdAt: -1 }).skip(skip).limit(limit).populate('genres categories'),
    Movie.countDocuments(filter),
  ]);

  res.json({
    success: true,
    data: {
      movies,
      pagination: {
        page,
        limit,
        total,
        totalPages: Math.ceil(total / limit),
      },
    },
  });
});

export const publishMovie = asyncHandler(async (req: Request, res: Response) => {
  const movie = await Movie.findById(req.params.id);
  if (!movie) throw new ApiError(404, 'Movie not found');
  if (movie.status === 'processing') {
    throw new ApiError(400, 'Cannot publish movie while video is still processing');
  }
  movie.status = 'published';
  await movie.save();
  res.json({ success: true, data: { movie } });
});

export const unpublishMovie = asyncHandler(async (req: Request, res: Response) => {
  const movie = await Movie.findById(req.params.id);
  if (!movie) throw new ApiError(404, 'Movie not found');
  movie.status = 'draft';
  await movie.save();
  res.json({ success: true, data: { movie } });
});

export const toggleFeatured = asyncHandler(async (req: Request, res: Response) => {
  const movie = await Movie.findById(req.params.id);
  if (!movie) throw new ApiError(404, 'Movie not found');
  movie.isFeatured = !movie.isFeatured;
  await movie.save();
  res.json({ success: true, data: { movie } });
});

export const toggleTrending = asyncHandler(async (req: Request, res: Response) => {
  const movie = await Movie.findById(req.params.id);
  if (!movie) throw new ApiError(404, 'Movie not found');
  movie.isTrending = !movie.isTrending;
  await movie.save();
  res.json({ success: true, data: { movie } });
});
