import { Schema, model, Document, Types } from 'mongoose';
import { IQualityVariant } from './Movie';

export interface ITranscodeJob extends Document {
  status: 'queued' | 'processing' | 'completed' | 'failed';
  progress: number;
  hlsMasterPlaylistUrl: string;
  qualities: IQualityVariant[];
  originalName: string;
  size: number;
  mimeType: string;
  error?: string;
  autoGeneratedPosterUrl?: string;
  movieId?: Types.ObjectId;
  episodeId?: Types.ObjectId;
  createdAt: Date;
  updatedAt: Date;
}

const transcodeJobSchema = new Schema<ITranscodeJob>(
  {
    status: {
      type: String,
      enum: ['queued', 'processing', 'completed', 'failed'],
      default: 'queued',
      required: true,
    },
    progress: { type: Number, default: 0, min: 0, max: 100 },
    hlsMasterPlaylistUrl: { type: String, required: true },
    qualities: [
      {
        resolution: { type: String, enum: ['240p', '360p', '480p', '720p', '1080p'], required: true },
        url: { type: String, required: true },
        bitrate: { type: Number },
      },
    ],
    originalName: { type: String, required: true },
    size: { type: Number, required: true },
    mimeType: { type: String, required: true },
    error: { type: String },
    autoGeneratedPosterUrl: { type: String, default: '' },
    movieId: { type: Schema.Types.ObjectId, ref: 'Movie' },
    episodeId: { type: Schema.Types.ObjectId, ref: 'Episode' },
  },
  { timestamps: true }
);

transcodeJobSchema.index({ status: 1 });
transcodeJobSchema.index({ hlsMasterPlaylistUrl: 1 }, { unique: true });

export const TranscodeJob = model<ITranscodeJob>('TranscodeJob', transcodeJobSchema);
